--------------------------------------------------------
--  已建立檔案 - 星期四-9月-17-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "FROGUSER"."ORDERS" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 17 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER(10,0), 
	"ORDER_DATE" TIMESTAMP (6), 
	"TOTAL_PRICE" NUMBER(10,0)
   ) ;
--------------------------------------------------------
--  DDL for Table ORDER_ITEMS
--------------------------------------------------------

  CREATE TABLE "FROGUSER"."ORDER_ITEMS" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 13 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ORDER_ID" NUMBER(10,0), 
	"PRODUCT_ID" NUMBER(10,0), 
	"QUANTITY" NUMBER(10,0), 
	"UNIT_PRICE" NUMBER(10,0)
   ) ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "FROGUSER"."PRODUCTS" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(100 CHAR), 
	"CATEGORY" VARCHAR2(50 CHAR), 
	"PRICE" NUMBER(10,0), 
	"STOCK" NUMBER(10,0)
   ) ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "FROGUSER"."USERS" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USERNAME" VARCHAR2(45 CHAR), 
	"PASSWORD" VARCHAR2(255 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Index IDX_ITEMS_ORDER
--------------------------------------------------------

  CREATE INDEX "FROGUSER"."IDX_ITEMS_ORDER" ON "FROGUSER"."ORDER_ITEMS" ("ORDER_ID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_ITEMS_PRODUCT
--------------------------------------------------------

  CREATE INDEX "FROGUSER"."IDX_ITEMS_PRODUCT" ON "FROGUSER"."ORDER_ITEMS" ("PRODUCT_ID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_ORDERS_USER
--------------------------------------------------------

  CREATE INDEX "FROGUSER"."IDX_ORDERS_USER" ON "FROGUSER"."ORDERS" ("USER_ID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_ORDERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FROGUSER"."PK_ORDERS" ON "FROGUSER"."ORDERS" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_ORDER_ITEMS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FROGUSER"."PK_ORDER_ITEMS" ON "FROGUSER"."ORDER_ITEMS" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_PRODUCTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FROGUSER"."PK_PRODUCTS" ON "FROGUSER"."PRODUCTS" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_USERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FROGUSER"."PK_USERS" ON "FROGUSER"."USERS" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index UK_USERS_USERNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "FROGUSER"."UK_USERS_USERNAME" ON "FROGUSER"."USERS" ("USERNAME") 
  ;
--------------------------------------------------------
--  DDL for Index PK_ORDERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FROGUSER"."PK_ORDERS" ON "FROGUSER"."ORDERS" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_ORDERS_USER
--------------------------------------------------------

  CREATE INDEX "FROGUSER"."IDX_ORDERS_USER" ON "FROGUSER"."ORDERS" ("USER_ID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_ORDER_ITEMS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FROGUSER"."PK_ORDER_ITEMS" ON "FROGUSER"."ORDER_ITEMS" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_ITEMS_ORDER
--------------------------------------------------------

  CREATE INDEX "FROGUSER"."IDX_ITEMS_ORDER" ON "FROGUSER"."ORDER_ITEMS" ("ORDER_ID") 
  ;
--------------------------------------------------------
--  DDL for Index IDX_ITEMS_PRODUCT
--------------------------------------------------------

  CREATE INDEX "FROGUSER"."IDX_ITEMS_PRODUCT" ON "FROGUSER"."ORDER_ITEMS" ("PRODUCT_ID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_PRODUCTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FROGUSER"."PK_PRODUCTS" ON "FROGUSER"."PRODUCTS" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_USERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FROGUSER"."PK_USERS" ON "FROGUSER"."USERS" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index UK_USERS_USERNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "FROGUSER"."UK_USERS_USERNAME" ON "FROGUSER"."USERS" ("USERNAME") 
  ;
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "FROGUSER"."ORDERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FROGUSER"."ORDERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "FROGUSER"."ORDERS" MODIFY ("ORDER_DATE" NOT NULL ENABLE);
  ALTER TABLE "FROGUSER"."ORDERS" MODIFY ("TOTAL_PRICE" NOT NULL ENABLE);
  ALTER TABLE "FROGUSER"."ORDERS" ADD CONSTRAINT "PK_ORDERS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDER_ITEMS
--------------------------------------------------------

  ALTER TABLE "FROGUSER"."ORDER_ITEMS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FROGUSER"."ORDER_ITEMS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "FROGUSER"."ORDER_ITEMS" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "FROGUSER"."ORDER_ITEMS" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "FROGUSER"."ORDER_ITEMS" MODIFY ("UNIT_PRICE" NOT NULL ENABLE);
  ALTER TABLE "FROGUSER"."ORDER_ITEMS" ADD CONSTRAINT "PK_ORDER_ITEMS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "FROGUSER"."PRODUCTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FROGUSER"."PRODUCTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "FROGUSER"."PRODUCTS" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "FROGUSER"."PRODUCTS" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "FROGUSER"."PRODUCTS" MODIFY ("STOCK" NOT NULL ENABLE);
  ALTER TABLE "FROGUSER"."PRODUCTS" ADD CONSTRAINT "PK_PRODUCTS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "FROGUSER"."USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FROGUSER"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "FROGUSER"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "FROGUSER"."USERS" ADD CONSTRAINT "PK_USERS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "FROGUSER"."USERS" ADD CONSTRAINT "UK_USERS_USERNAME" UNIQUE ("USERNAME")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "FROGUSER"."ORDERS" ADD CONSTRAINT "FK_ORDERS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "FROGUSER"."USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDER_ITEMS
--------------------------------------------------------

  ALTER TABLE "FROGUSER"."ORDER_ITEMS" ADD CONSTRAINT "FK_ITEMS_ORDER" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "FROGUSER"."ORDERS" ("ID") ENABLE;
  ALTER TABLE "FROGUSER"."ORDER_ITEMS" ADD CONSTRAINT "FK_ITEMS_PRODUCT" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "FROGUSER"."PRODUCTS" ("ID") ENABLE;
